name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Vercel Secrets
      run: |
        echo "Testing Vercel secrets..."
        if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "✅ VERCEL_TOKEN is set"
        else
          echo "❌ VERCEL_TOKEN is not set"
        fi
        
        if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
          echo "✅ VERCEL_ORG_ID is set"
        else
          echo "❌ VERCEL_ORG_ID is not set"
        fi
        
        if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
          echo "✅ VERCEL_PROJECT_ID is set"
        else
          echo "❌ VERCEL_PROJECT_ID is not set"
        fi 